const STYLE_ATTRS = [
    'width',
    'height',
    'minWidth',
    'minHeight',
    'maxWidth',
    'maxHeight',
    'padding',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
    'paddingX',
    'paddingY',
    'margin',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'marginX',
    'marginY',
    'borderWidth',
    'borderColor',
    'borderStyle',
    'borderBg',
    'borderBackgroundColor',
    'borderTopBackgroundColor',
    'borderRightBackgroundColor',
    'borderBottomBackgroundColor',
    'borderLeftBackgroundColor',
    'borderTopLeftBackgroundColor',
    'borderTopRightBackgroundColor',
    'borderBottomLeftBackgroundColor',
    'borderBottomRightBackgroundColor',
    'borderTop',
    'borderRight',
    'borderBottom',
    'borderLeft',
    'backgroundColor',
    'color',
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'dim',
    'inverse',
    'flexDirection',
    'flexWrap',
    'flexGrow',
    'flexShrink',
    'flexBasis',
    'justifyContent',
    'alignItems',
    'alignSelf',
    'alignContent',
    'gap',
    'rowGap',
    'columnGap',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'display',
    'zIndex',
    'anchorName',
    'positionAnchor',
    'positionArea',
    'positionTry',
    'positionTryFallbacks',
    'positionTryOrder',
    'positionVisibility',
    'whiteSpace',
    'wordBreak',
    'overflowWrap',
    'textWrap',
] as const;

const CSS_PROP_MAP: Record<string, string> = {
    'min-width': 'minWidth',
    'min-height': 'minHeight',
    'max-width': 'maxWidth',
    'max-height': 'maxHeight',
    'background-color': 'backgroundColor',
    'border-color': 'borderColor',
    'border-style': 'borderStyle',
    'border-width': 'borderWidth',
    'border-bg': 'borderBg',
    'border-background-color': 'borderBackgroundColor',
    'border-top-background-color': 'borderTopBackgroundColor',
    'border-right-background-color': 'borderRightBackgroundColor',
    'border-bottom-background-color': 'borderBottomBackgroundColor',
    'border-left-background-color': 'borderLeftBackgroundColor',
    'border-top-left-background-color': 'borderTopLeftBackgroundColor',
    'border-top-right-background-color': 'borderTopRightBackgroundColor',
    'border-bottom-left-background-color': 'borderBottomLeftBackgroundColor',
    'border-bottom-right-background-color': 'borderBottomRightBackgroundColor',
    'flex-direction': 'flexDirection',
    'flex-wrap': 'flexWrap',
    'flex-grow': 'flexGrow',
    'flex-shrink': 'flexShrink',
    'flex-basis': 'flexBasis',
    'justify-content': 'justifyContent',
    'align-items': 'alignItems',
    'align-self': 'alignSelf',
    'align-content': 'alignContent',
    'row-gap': 'rowGap',
    'column-gap': 'columnGap',
    'z-index': 'zIndex',
    'anchor-name': 'anchorName',
    'position-anchor': 'positionAnchor',
    'position-area': 'positionArea',
    'position-try': 'positionTry',
    'position-try-fallbacks': 'positionTryFallbacks',
    'position-try-order': 'positionTryOrder',
    'position-visibility': 'positionVisibility',
    'white-space': 'whiteSpace',
    'word-break': 'wordBreak',
    'overflow-wrap': 'overflowWrap',
    'word-wrap': 'overflowWrap',
    'text-wrap': 'textWrap',
};

export const STYLE_ATTR_CANON = new Map<string, string>();
for (const attr of STYLE_ATTRS) {
    STYLE_ATTR_CANON.set(attr, attr);
    STYLE_ATTR_CANON.set(attr.toLowerCase(), attr);
}
for (const [cssName, mapped] of Object.entries(CSS_PROP_MAP)) {
    STYLE_ATTR_CANON.set(cssName, mapped);
    STYLE_ATTR_CANON.set(cssName.toLowerCase(), mapped);
}

export const NUMERIC_STYLE_PROPS = new Set<string>([
    'width',
    'height',
    'minWidth',
    'minHeight',
    'maxWidth',
    'maxHeight',
    'padding',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
    'margin',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'borderWidth',
    'gap',
    'rowGap',
    'columnGap',
    'zIndex',
]);

export function canonicalizeStyleProp(name: string | undefined | null): string | undefined {
    if (!name) return undefined;
    return (
        STYLE_ATTR_CANON.get(name) ??
        (typeof name === 'string' ? STYLE_ATTR_CANON.get(name.toLowerCase()) : undefined)
    );
}
